### ISSUE TITLE
Open Source the templates

### ISSUE THREAD

**Issue by marado** [chrisjrob/latex-templates#1]
Hi there,

The README states "Copyright (C) 2013", and there's no LICENSE file.
If would be nice if you would license these templates, so people would be able to use, distribute and enhance them.

**Comment by chrisjrob** [comment]
Added GPL licence hope that is sufficient.

Thanks for raising the issue.

Chris.

On 19 October 2015 at 16:15, Marcos Marado notifications@github.com wrote:

> Hi there,
> 
> The README states "Copyright (C) 2013", and there's no LICENSE file.
> If would be nice if you would license these templates, so people would be
> able to use, distribute and enhance them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrisjrob/latex-templates/issues/1.

## 

Regards,
Chris.

**Comment by marado** [comment]
It is, thank you.
